development:
  theme_id: 184027085
  password: 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
  store: omgstores.myshopify.com
  bucket_size: 40
  refill_rate: 2
  concurrency: 2
  timeout: 30s
  ignore_files:
    - .git/*
    - .gitignore
    - .idea
    - dev/*
    - node_modules/*
    - package.json
    - package-lock.json
